### ISSUE TITLE
LanguageProgress is not populated in a fresh dev environment

### ISSUE THREAD

**Issue by JoelNiemela** [globalbibletools/platform#16]
When setting up my local dev environment, I initially got this error:
```
materialized view "LanguageProgress" has not been populated"
```

This can be resolved by running this command in PostgreSQL:
```sql
REFRESH MATERIALIZED VIEW "LanguageProgress";
```

Ideally, this shouldn't be needed at all (I feel like some setup script somewhere should take care of this), but if nothing else, a note to this effect could be added to the `README.md` until a proper solution can be made.

**Comment by arrocke** [comment]
If we cannot restore a materialized view from a database dump, we should add a script to `db/docker-initdb.sh` that refreshes the materialized view after the data has been restored from the dump file
