### ISSUE TITLE
Languages in Alphabetical Order

### ISSUE THREAD

**Issue by BethedenMinistries** [globalbibletools/platform#50]
### Precheck

- [X] I have searched the issues list for similar ideas.

### Problem

Now that there are a lot of languages in the admin panel, it's difficult to scan through quickly and find the one you want because they seem to be in random order. 

### Solutions

Order the languages in alphabetical order by their English name equivalent.

### Urgency

Low (An idea I want to log, but doesn't need immediate attention)

**Comment by arrocke** [comment]
I'm going to close this since I added it to be handled in #18.
